FROM python:3.8

WORKDIR /src/app

COPY requirements.txt /src/app

RUN pip install --upgrade pip

RUN pip install -r requirements.txt

COPY streamlit.py /src/app

RUN apt-get update && apt-get install -y \
    build-essential \
    curl \
    software-properties-common \
    git \
    && rm -rf /var/lib/apt/lists/*

EXPOSE 8501

EXPOSE 80

CMD ["streamlit", "run", "streamlit.py", "--server.port=80", "--server.address=0.0.0.0"]



